### PR TITLE
Fixes #1 and #3 and a few other bugs, so that it can work from scratch from github source with Love 0.9.2

### LINKED ISSUE #1: Doesn't work with love 0.9.0+
Some functions like love.graphics.setMode have moved.

### PR DESCRIPTION
**Pull request by KevinField**

### CODE REVIEW

**Comment by KevinField** [comment]
I guess that should read "#1 and #2".  For some reason I could have sworn I had closed #2 and left #3 open.

**Comment by Germanunkol** [comment]
Hey, cool, thanks for the updates!

I'm running Löve 0.9.1 (which shouldn't be different in API from 0.9.2) and I get: "main.lua:227: module 'utf8' not found:"

It's been a while since I worked on this and I haven't looked into it yet, but is this something you changed?

Edit: Yes, seems like this is new. Could you add the file?
utff8 support is something which was really missing here before (Löve 0.7 had issues with that) - awesome, thanks for adding it!

**Comment by KevinField** [comment]
This is something I changed (the keypress event got split out in 0.9.2) 
but utf8 being missing would be a lua thing.  Not sure which lua version 
you're on but an update might help?  Or maybe whichever lua comes with 
love 0.9.2 would be new enough to have the utf8 module?

Thanks,
Kev

**Comment by Germanunkol** [comment]
Huh, you're right, it's been added to Löve in version 0.9.2.
Quote from the changelog:
"Added Lua 5.3's UTF-8 module, via utf8 = require("utf8"). "

It works with this new version!

**Comment by KevinField** [comment]
Hmm, for some reason, even with conf.lua in the same dir as main.lua, and containing the function setting resizing to true, it doesn't seem resizeable on Linux Mint 17.  But there's another thing, if you make it small enough that it's easy to resize on small displays, it won't be big enough by default on big displays.  Maybe we need some branching code.  Or, we could do fullscreen and try to have the UI adapt to whatever that happens to be.

**Comment by KevinField** [comment]
I just tried fullscreen, and it did something interesting: my screen flickered black, then the desktop manager returned but had a different style, and then it came back to normal, and the game behaved as before.  So that doesn't help, at least on my machine.

**Comment by KevinField** [comment]
But it does mean I have conf.lua in the right place and that it's having an effect.  Just interesting that the window can't resize.

**Comment by KevinField** [comment]
If I set fullscreentype to desktop it doesn't do anything at all.

**Comment by KevinField** [comment]
Interestingly, passing resizable to the window constructor instead does actually make it resizeable.

**Comment by KevinField** [comment]
Okay, here's something that will work for you, and then if I want it to work better on my tiny display, I'll have to adapt the status message function a bit maybe (welcome shows up mixed with the quit button.)  It seems that setting `resizable = true` also makes it so that passing the original size in automatically caps it at the screen size.

**Pull request merged**
